.catalog:
  name: "thalshop"
  version: "0.6.9"
  description: "Library service powered by Meanshop"
  uuid: thalshopextdb-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "MEANSHOP_HOST"
        description: "Hostname to use for the MEANSHOP server"
        label: "MEANSHOP Hostname"
        required: true
        default: "meanshop"
        type: "string"
      - variable: "MEANSHOP_DOMAIN"
        description: "Domain to use for the MEANSHOP server"
        label: "MEANSHOP Domain"
        required: true
        default: "example.com"
        type: "string"
      - variable: "PORT"
        description: "Port to use for the MEANSHOP server"
        label: "MEANSHOP Port"
        required: true
        default: "3547"
        type: "int"
      - variable: "MEANGO_HOST"
        description: "Mongo Host to use for the MEANSHOP server"
        label: "Mongo Host"
        required: true
        default: "mymongo_host"
        type: "string"
      - variable: "MEANGO_DEBUG"
        description: "include debug data in stdout"
        label: "debug"
        required: false
        type: "string"
      - variable: host_label
        label: "Host Label to Meanshop Tags"
        description: |
          Host label to use as Meanshop 'value' tag.
          Example: 'meanshop=true'
        required: false
        default: "meanshop=true"
        type: "string"

thalhalla-nginx:
  scale: 1
  retain_ip: true

thalhalla-node:
  scale: 1
  retain_ip: true
