version: '2'
catalog:
  name: "dockarmaiii-wasteland"
  version: "0.2.5"
  decription: A reliable ArmA3 Dedicated steam server
  uuid: thalhalla-wasteland-0
  minimum_rancher_version: v0.51.0
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: ""
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: true
        default: ""
        type: "password"
      - variable: "STEAM_GID"
        description: "App ID or GID from steam to use for the server"
        label: "Steam Game ID"
        required: true
        default: "233780"
        type: "string"
      - variable: "IP"
        description: "IP to associate with this server"
        label: "IP"
        required: true
        default: "0.0.0.0"
        type: "string"
      - variable: "PORT2"
        description: "VON PORT to associate with this server"
        label: "PORT2"
        required: true
        default: "2302"
        type: "string"
      - variable: "PORT3"
        description: "2303 PORT to associate with this server"
        label: "PORT3"
        required: true
        default: "2303"
        type: "string"
      - variable: "PORT4"
        description: "2304 to associate with this server"
        label: "PORT4"
        required: true
        default: "2304"
        type: "string"
      - variable: "PORT5"
        description: "2305 PORT to associate with this server"
        label: "PORT5"
        required: true
        default: "2305"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "rancher-nfs"
        type: enum
        options: # List of options if using type of `enum`
          - rancher-nfs
          - rancher-efs
          - rancher-ebs
          - convoy-nfs
          - convoy-efs
          - convoy-ebs
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "ARMA3WASTELAND"
        type: "string"
      - variable: "GAME_PASSWORD"
        description: "Admin Password to use for the server"
        label: "Game Password"
        required: false
        default: ""
        type: "password"
      - variable: "ADMIN_PASSWORD"
        description: "Admin Password to use for the server"
        label: "Admin Password"
        required: true
        default: ""
        type: "password"
      - variable: "STEAMER_FILE"
        description: "The steamer file name"
        label: "command"
        required: true
        default: "steamer.txt"
        type: "string"
      - variable: "DOCKARMAIII_COMMAND"
        description: "The command name to associate with this server"
        label: "command"
        required: true
        default: "/assets/controller.sh"
        type: "string"
      - variable: "DOCKARMAIII_TAG"
        description: "The command name to associate with this server"
        label: "TAG"
        required: true
        default: "latest"
        type: "string"
      - variable: "DOCKARMAIII_MODS"
        description: "The mods to associate with this server"
        label: "MODS"
        required: false
        default: "@acex"
        type: "string"
      - variable: "DOCKARMAIII_SERVER_MODS"
        description: "The mods to associate with this server"
        label: "MODS"
        required: false
        default: "@acex"
        type: "string"
      - variable: "HOSTNAME"
        description: "The hostname to associate with this server"
        label: "HOSTNAME"
        required: true
        default: "Thalhalla.com-247-WasteLand"
        type: "string"
      - variable: "MAX_PLAYERS"
        description: "The max players to associate with this server"
        label: "Max Players"
        required: true
        default: "64"
        type: "string"
      - variable: "host_label"
        description: "Host label where to run this service."
        label: "Host label:"
        required: true
        default: "public=true"
        type: "string"
      - variable: "EXTDB_HOST"
        description: "The IP/Hostname of your ExtDB(MySQL) server"
        label: "ExtDB Host"
        required: true
        default: ""
        type: "string"
      - variable: "EXTDB_USERNAME"
        description: "The user for your ExtDB(MySQL) server"
        label: "ExtDB Username"
        required: true
        default: ""
        type: "string"
      - variable: "EXTDB_PASSWORD"
        description: "The password for your ExtDB(MySQL) server"
        label: "ExtDB Password"
        required: true
        default: ""
        type: "password"
      - variable: "EXTDB_PORT"
        description: "The port for your ExtDB(MySQL) server"
        label: "ExtDB Port"
        required: true
        default: "3306"
        type: "string"
services:
  dockarmaiii-wasteland:
    config:
     node.name: "$${HOSTNAME}"
    scale: 1
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 360000
      unhealthy_threshold: 9
      strategy: none
      healthy_threshold: 2
      response_timeout: 9000
  dockarmaiiihc1:
    scale: 1
  dockarmaiiihc2:
    scale: 1
  dockarmaiii-datavolume:
    scale: 1
