.catalog:
  name: "dockarmaiii"
  version: "0.3.1"
  decription: A reliable ArmA3 Dedicated steam server
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: ""
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: true
        default: ""
        type: "password"
      - variable: "PORT"
        description: "main PORT to associate with this server"
        label: "PORT"
        required: true
        default: "2302"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server (convoy-nfs,convoy-efs,convoy-ebs)"
        label: "VOLUME Driver"
        required: true
        default: "convoy-nfs"
        type: "string"
      - variable: "VOLUME_NAME"
        description: "The VOLUME name to associate with this server"
        label: "VOLUME Name"
        required: true
        default: "ARMA3"
        type: "string"
      - variable: "DOCKARMAIII_COMMAND"
        description: "The command name to associate with this server"
        label: "command"
        required: true
        default: "/assets/valve-run.sh"
        type: "string"
      - variable: "DOCKARMAIII_BRANCH"
        description: "The command name to associate with this server"
        label: "BRANCH"
        required: true
        default: "latest"
        type: "string"
      - variable: "HOSTNAME"
        description: "The name to associate with this server"
        label: "ServerName"
        required: true
        default: "Thalhalla.com-247-fustercluck"
        type: "string"
dockarmaiii:
  metadata:
    dockarmaiii:
      config:
       node.name: "$${HOSTNAME}"
