.catalog:
  name: "dockarmaiii"
  version: 0.14.0-HalvarRackesh
  decription: A reliable ArmA3 Dedicated steam server 0.14.0 Halvar Rackesh
  questions:
      - variable: "STEAM_USERNAME"
        description: "Username from steam to use for the server"
        label: "Steam Username"
        required: true
        default: ""
        type: "string"
      - variable: "STEAM_PASSWORD"
        description: "Password from steam to use for the server"
        label: "Steam Password"
        required: true
        default: ""
        type: "password"
      - variable: "ADMIN_PASSWORD"
        description: "Admin Password to use for the server"
        label: "Admin Password"
        required: true
        default: ""
        type: "password"
      - variable: "PORT"
        description: "Primary PORT to associate with this server"
        label: "PORT"
        required: true
        default: "2302"
        type: "string"
      - variable: "PORT2"
        description: "2nd PORT to associate with this server"
        label: "PORT2"
        required: true
        default: "2303"
        type: "string"
      - variable: "PORT3"
        description: "3rd PORT to associate with this server"
        label: "PORT3"
        required: true
        default: "2304"
        type: "string"
      - variable: "PORT4"
        description: "4th PORT to associate with this server"
        label: "PORT4"
        required: true
        default: "2305"
        type: "string"
      - variable: "VOLUME_DRIVER"
        description: "The VOLUME driver to associate with this server"
        label: "VOLUME Driver"
        required: true
        default: "rancher-nfs"
        type: enum
        options: # List of options if using type of `enum`
          - rancher-nfs
          - rancher-efs
          - rancher-ebs
      - variable: "DATA_VOLUME_NAME"
        description: "The DATA VOLUME name to associate with this server"
        label: "DATA VOLUME Name"
        required: true
        default: "ARMA3_DATA"
        type: "string"
      - variable: "DOCKARMAIII_COMMAND"
        description: "The command name to associate with this server"
        label: "command"
        required: true
        default: "/assets/dockarmaiii"
        type: "string"
      - variable: "DOCKARMAIII_BRANCH"
        description: "The command name to associate with this server"
        label: "BRANCH"
        required: true
        default: "0.14.0"
        type: "string"
      - variable: "HOSTNAME"
        description: "The name to associate with this server"
        label: "ServerName"
        required: true
        default: "Thalhalla.com-247-fustercluck"
        type: "string"
      - variable: "MAX_PLAYERS"
        description: "The max players to associate with this server"
        label: "Max Players"
        required: true
        default: "64"
        type: "string"
      - variable: "BUILD_ENABLED"
        description: "Is this a build enabled Server?"
        label: "Build Enabled"
        required: true
        default: true
        type: "boolean"
      - variable: "WASTELAND_ENABLED"
        description: "Is this a A3Wasteland Server?"
        label: "Wasteland Enabled"
        required: true
        default: true
        type: "boolean"
      - variable: "OVERWATCH_ENABLED"
        description: "Is this an OVERWATCH Server?"
        label: "OVERWATCH Enabled"
        required: true
        default: true
        type: "boolean"
      - variable: "host_label"
        description: "Host label where to run this service."
        label: "Host label:"
        required: true
        default: "public=true"
        type: "string"
dockarmaiii:
  metadata:
    dockarmaiii:
      config:
       node.name: "$${HOSTNAME}"
